#!/bin/sh

cd ~
git config --global user.name "Yihui Xie"
git config --global user.email "xie@yihui.name"

[ ! -d R ] && mkdir R
wget -q http://yihui.name/xran/.Renviron
wget -q http://yihui.name/xran/.Rprofile
ls -al

R -e 'sapply(.libPaths(), list.files); sessionInfo()'

