#!/bin/sh

cd ..
rm -f *_*.tar.gz
R_PKG=$(basename $TRAVIS_REPO_SLUG)
R CMD build $R_PKG &> /dev/null
git clone --quiet https://${GH_TOKEN}@github.com/yihui/xran.git ~/xran > /dev/null
rm -f ~/xran/src/contrib/$R_PKG_*.tar.gz
cp *_*.tar.gz ~/xran/src/contrib/
cd ~/xran/
Rscript -e "tools::write_PACKAGES('src/contrib', 'source')"
git add * && git commit --amend -m"Add new packages from Travis build $TRAVIS_BUILD_NUMBER" && git push -f origin gh-pages
