#!/bin/sh

set -e

[ "${TRAVIS_PULL_REQUEST}" != "false" ] && exit 0
[ -z "${R_PKG}" ] && exit 0

ls $R_PKG*.tar.gz || cd ..
R CMD INSTALL $R_PKG*.tar.gz

echo "Uploading the package $R_PKG"
git clone --quiet https://${GH_TOKEN}@github.com/yihui/xran.git ~/xran > /dev/null
rm -f ~/xran/src/contrib/${R_PKG}_*.tar.gz
cp ${R_PKG}_*.tar.gz ~/xran/src/contrib/
cd ~/xran/
Rscript -e "tools::write_PACKAGES('src/contrib', 'source')"
Rscript homepage.R
git add -A
git commit --amend -m"add new packages from Travis build $TRAVIS_BUILD_NUMBER ($TRAVIS_REPO_SLUG)"
git rebase origin/master
git push -fq origin gh-pages > /dev/null
